[main]
# shell=tmux new -A
# font=SauceCodePro Nerd Font:size=11.5
font=Monocraft Nerd Font:size=10
resize-delay-ms=0
pad=0x0 center

# Search 'SECTION: colors' in 'man foot.ini'.
[colors-dark]
alpha=0.97
alpha-mode=all

# carbonfox
background=0c0c0c
foreground=f2f2f2
selection-background=2a2a2a
regular0=282828
regular1=e85c51
regular2=25be6a
regular3=ebcb8b
regular4=78a9ff
regular5=be95ff
regular6=63cdcf
regular7=dfdfe0
bright0=4a4a4a
bright1=ef8c85
bright2=5ddf98
bright3=f1daac
bright4=a3c5ff
bright5=d9c2ff
bright6=92dcdd
bright7=eaeaeb
dim0=242424
dim1=c54e45
dim2=20a25a
dim3=d9b263
dim4=4287ff
dim5=9757ff
dim6=40c2c4
dim7=bebec1
