[main]
# shell=tmux new -A
font=SauceCodePro Nerd Font:size=11.5
resize-delay-ms=0
pad=0x0 center

# Search 'SECTION: colors' in 'man foot.ini'.
[colors-dark]
alpha=0.97
alpha-mode=all

# carbonfox
background=0c0c0c
foreground=f2f4f8
selection-background=2a2a2a
regular0=282828
regular1=ee5396
regular2=25be6a
regular3=ebcb8b
regular4=78a9ff
regular5=be95ff
regular6=33b1ff
regular7=dfdfe0
bright0=4a4a4a
bright1=f16fa7
bright2=37d77f
bright3=eed29b
bright4=8fb8ff
bright5=c6a3ff
bright6=52bdff
bright7=e5e5e6
dim0=242424
dim1=ea2a7d
dim2=20a25a
dim3=e3b559
dim4=4287ff
dim5=9757ff
dim6=059fff
dim7=bebec1
